### ISSUE TITLE
Are generated serial numbers unique?

### ISSUE THREAD

**Issue by dermyrddin** [nicolas314/2cca#3]
Is I know, os.urandom is the best random generator, but it not guarantees that generated numbers is totally unique.

uuid.uuid otherwise guarantees unique numbers, but less random and therefore less secure.

So is it possible to recieve serial number collisions on a very big amount of generated certs?

**Comment by nicolas314** [comment]
Hi Merlin,
There is no way you can guarantee serial number unicity when the generators are not linked to one another, as for UUID generators. A cryptographically strong random number generator will not change anything to that: your python script may have generated the same number as my Python script and we would not know, and it is not important anyway because our randomly generated UUIDs do not live in the same space: your certificates, and mine.
As a rule of thumb, you will need to generate N/2 random numbers of N bits before observing collisions, assuming a decent enough random generator. The exact math are a bit more complicated than that, look for 'birthday attacks' if you need more. Applying this simplified rule, we have 112 actual random bits in a 2cca serial number (=128-16) so you would need to produce 2^56 = 72,057,594,037,927,936 certificates before having a reasonable chance of observing a collision.
Cheers
